apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: "{{ .Values.app.name }}-container"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: MONGO_URI
            value: app-mongodb-headless
          - name: MONGO_USERNAME
            value: root
          - name: MONGO_PASS
            value: "password"
          envFrom:
          - configMapRef:
              name: "{{ .Values.app.name }}-conf"
          - secretRef:
              name: "{{ .Values.app.name }}-db-auth"
          ports:
            - containerPort: {{ .Values.service.applicationPort }}
          resources:
            requests:
              cpu: {{ .Values.app.requestsCPU }}
              memory: {{ .Values.app.requestsMemory }}
            limits:
              cpu: {{ .Values.app.maxCPU }}
              memory: {{ .Values.app.maxMemory }}