apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.app.name }}-db-auth"
stringData:
  MONGODB_URI: mongodb://{{ index .Values.mongodb.auth.usernames 0 }}:{{ index .Values.mongodb.auth.passwords 0 }}}@{{ .Values.mongodb.fullnameOverride }}-0.{{ .Values.mongodb.fullnameOverride }}-headless:27017,{{ .Values.mongodb.fullnameOverride }}-1.{{ .Values.mongodb.fullnameOverride }}-headless:27017,{{ .Values.mongodb.fullnameOverride }}-2.{{ .Values.mongodb.fullnameOverride }}-headless:27017/{{ index .Values.mongodb.auth.databases 0 }}