# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-internal: "true"
#   name: "{{ .Values.app.name }}-clusterip"
# spec:
#   selector:
#     app: "{{ .Values.app.name }}"
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5000
#   type: LoadBalancer