# apiVersion: v1
# kind: Service
# metadata:
#   name: "{{ .Values.app.name }}-clusterip"
# spec:
#   selector:
#     app: "{{ .Values.app.name }}"
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5000