version: "3"
services:

  app:
    container_name: app
    build: .
    ports:
      - "5000:5000"
    links:
      - db


  db:
    container_name: mongodb
    image: mongo:latest
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=stav-db
    ports:
      - 27017:27017
