version: "3"
services:
  app:
    container_name: app
    build: .
    environment:
      - MONGO_URI=mongodb
      - MONGO_USERNAME=root
      - MONGO_PASS=pass
    ports:
      - "5000:5000"
    links:
      - db
    networks:
      - my-app

  db:
    container_name: mongodb
    image: mongo:latest
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=stav-db
    networks:
      - my-app

  nginx:
    image: nginx:1.20.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static/:/var/www/static/
    ports:
      - 80:80
    networks:
      - my-app
    depends_on:
      - app

networks:
    my-app:
