apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stav-app-argocd
  namespace: argocd
spec:
  project: default
  source:
    repolURL: https://github.com/stavShukrun/argo.git
    targetRevision: HEAD
    path: .
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true