apiVersion: v1
name: stav-app-helm
description: A Helm chart for deploying stav webapp for the DevOps bootcamp.
type: application
version: 1.0.0
appVersion: "v1"

dependencies:
  - name: mongodb
    version: "12.1.13"
    repository: "https://charts.bitnami.com/bitnami"
  - name: nginx-ingress-controller
    version: "9.2.10"
    repository: "https://charts.bitnami.com/bitnami"
