app:
  replicaCount: 3
  requestsCPU: "500m"
  requestsMemory: "512Mi"
  maxCPU: "1000m"
  maxMemory: "1024Mi"
  name: "vet-app"

service:
  type: ClusterIP
  port: 80
  applicationPort: 5000
  website: "stavcrm.ddns.net"

cronJob:
  schedule: "0 0 * * *"
  restartPolicy: OnFailiure

image:
  repository: 644435390668.dkr.ecr.eu-west-1.amazonaws.com/stav-app
  pullPolicy: Always
  tag: "1.0.0"

mongodb:
  architecture: "replicaset"
  replicaCount: 3
  fullnameOveride: "mongodb"
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
  auth:
    rootUser: root
    rootPassword: stav
    databases: ["stav-db"]
    usernames: ["root"]
    passwords: ["pass"]

controller:
  ingressClass: nginx