app:
  replicaCount: 3
  requestsCPU: "500m"
  requestsMemory: "128Mi"
  maxCPU: "1000m"
  maxMemory: "256Mi"
  name: "vet-app"

service:
  type: ClusterIP
  port: 80
  applicationPort: 5000
  website: "stav-vet.ddns.net"

cronJob:
  schedule: "0 0 * * *"
  restartPolicy: OnFailiure

image:
  repository: 644435390668.dkr.ecr.eu-west-1.amazonaws.com/stav-app
  pullPolicy: Always
  tag: '1.0.4'

mongodb:
  architecture: "replicaset"
  replicaCount: 3
  auth:
    enabled: true
    rootUser: root
    rootPassword: password
    databases: ["stav"]
    usernames: ["stav"]
    passwords: ["12345678"]

controller:
  ingressClass: nginx