version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
