apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stav-app-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stavShukrun/devops-app.git
    targetRevision: HEAD
    path: ./terraform/charts/stav-app-helm
  destination:
    server: https://vet-app-clusterip.default.svc
    namespace: default
    
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true