apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo
  namespace: default
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/stavShukrun/devops-app.git
  passwords: stav123
  username: stav
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stav-app-argocd
  namespace: argocd
spec:
  project: default
  source:
    repolURL: https://github.com/stavShukrun/devops-app.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
    
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true