apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stav-app-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/stavShukrun/devops-app.git
    targetRevision: HEAD
    path: ./terraform/charts/stav-app-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: default
    
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argoc
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 23.3.1
    helm:
      values: |
        fullnameOverride: prometheus
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  resources:
                    requests:
                      storage: 1Gi
        grafana:
          grafana.ini:
            feature_toggles:
              enable: tempoSearch
          persistence:
            type: statefulset
            enabled: true
            size: 5Gi 
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
              - name: Loki
                type: loki
                uid: Loki
                access: proxy
                editable: false
                url: http://loki-gateway.monitoring:80 
                jsonData:                     
                  derivedFields:
                    - datasourceUid: Tempo
                      matcherRegex: "(?:traceID|traceId)(?:=|\\s)(\\w+)"
                      name: TraceID
                      url: "$${__value.raw}"
              - name: Tempo
                type: tempo
                uid: Tempo
                access: proxy
                editable: false
                url: http://tempo-gateway.monitoring:80
          sidecar:                              
            dashboards:
              enabled: true  
              label: grafana_dashboard 
              folder: /tmp/dashboards
              searchNamespace: ALL
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true